---

# Создаём рабочую директорию Redis
- name: Configure | Create work dir
  file:
    state: directory
    path: "{{ redis_dir }}"
    owner: root
    group: root

#  Копируем файл docker-compose.yml для запуска сервисов
- name: Configure | Configure docker-compose.yml file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ redis_dir }}/docker-compose.yml" 
    