stages:
  - build-project
  - build-docker
  - run-pretest

#  Собираем кэш мавена
.maven:
  image: $MAVEN_IMAGE
  tags:
    - projects_puv
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/.m2/repository

# Собираем проект
.build-project-tag:
  extends: .maven
  stage: build-project
  before_script:
    # Задаём переменные
    - export DATE_RELEASE=`date +%d%m%y`
    - apt-get update -y
    - apt-get install git -y
    # Подключаемся к текущему репозиторию гитлаба 
    - git remote set-url origin https://$GIT_USER:$GIT_PASS@$PROJECT_URL
    # Задаём e-mail пользователя для дальнейших изменений
    - git config --global user.email "$GIT_EMAIL_USER"
    # Задаём имя пользователя для дальнейших изменений
    - git config --global user.name "$GIT_USER"
  script:
    # Забираем последний тег, если он существует, если нет, приравниваем значение к 0
    - if git describe --tags --abbrev=0 > /dev/null; then LAST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)); else LAST_TAG=0.0.0; fi
    # Выделяем номер последней сборки из тега и инкриментим
    - BUILD_NUMBER=$(echo $LAST_TAG |  awk -F'.' '{print $3+1}')
    # Забираем текуший номер версии из pom ( в формате <major>.<minor>)
    - version=$(mvn -f ./Modules/pom.xml org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)
    - pref=$(echo $version |  awk -F'.' '{print $1"."$2}')
    # Формируем новую версию в формате <major>.<minor>.<номер сборки> TODO: добавить суффикс (dev, RC или "") в зависимости от ветки
    - NEWVERSION=$(echo $pref"."$BUILD_NUMBER)
    # обновляем номер версии в pom
    - mvn -f ./Modules/pom.xml -U versions:set -DnewVersion=${NEWVERSION}${SUFF}
    # Собираем артефакт
    - mvn -f ./Modules/pom.xml -e clean install -Dmaven.test.skip=true -Dzip.skip=true
    - mvn -f ./docker/pom.xml install -Dfunc.version=$DFUNC_VERSION -Dcore.version=$DCORE_VERSION
    # Возвращаем старую версию в pom
    - mvn -f ./Modules/pom.xml -U versions:set -DnewVersion=${version}
    # Создаем отсутствующую директорию webapps
    - mkdir ./docker/source/sufd/jetty/webapps
    # Перемещаем созданные файлы для оптимизации структуры 
    - mv ./docker/source/sufd/sufd-server.war ./docker/source/sufd/jetty/webapps/sufd-server.war
    - mv ./docker/source/sufd/sufd.config ./docker/source/sufd/jetty/sufd.config
    - mv ./docker/source/sufd/sql-migrations ./docker/source/sufd/jetty/sql-migrations
    # Создаем тэг
    - git tag -a $NEWVERSION.$DATE_RELEASE.$CI_PROJECT_NAME -m "version ${NEWVERSION}.${DATE_RELEASE}.${CI_PROJECT_NAME}"
    # Пушим тэг в текущую ветку  
    - git push origin $NEWVERSION.$DATE_RELEASE.$CI_PROJECT_NAME
  artifacts:
    paths:
      - ./docker/source/sufd/
    when: always
    reports:
      junit:
        - ./Modules/asfk-lib/target/surefire-reports/TEST-*.xml
        - ./Modules/asfk-lib/target/failsafe-reports/TEST-*.xml

.build-project:
  extends: .maven
  stage: build-project
  script:
    - mvn -version
    - mvn -f ./Modules/pom.xml -e clean install -Dmaven.test.skip=true -Dzip.skip=true
    - mvn -f ./docker/pom.xml install -Dfunc.version=$DFUNC_VERSION -Dcore.version=$DCORE_VERSION
    # Создаем отсутствующую директорию webapps
    - mkdir ./docker/source/sufd/jetty/webapps
    # Перемещаем созданные файлы для оптимизации структуры 
    - mv ./docker/source/sufd/sufd-server.war ./docker/source/sufd/jetty/webapps/sufd-server.war
    - mv ./docker/source/sufd/sufd.config ./docker/source/sufd/jetty/sufd.config
    - mv ./docker/source/sufd/sql-migrations ./docker/source/sufd/jetty/sql-migrations

build-project-branch:
  extends: .build-project
  only:
    - merge_requests
  except:
    - "develop"
    -  "master"
    - "/^release-\\w+/"
    - "tags"

build-project-dev:
  extends: .build-project
  only:
    - "develop"
  artifacts:
    paths:
      - ./docker/source/sufd/

build-project-release:
  extends: .build-project-tag
  only:
    - "/^release-\\w+/"
  variables:
    SUFF: "-rc"
  artifacts:
    paths:
      - ./docker/source/sufd/

build-project-master:
  extends: .build-project-tag
  only:
    - "master"
  variables:
    SUFF: ""
  artifacts:
    paths:
      - ./docker/source/sufd/

build-docker-pretest:
  stage: build-docker
  tags:
    - projects_puv
  only:
    - "/^release-\\w+/"
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u"$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG_PRETEST .
    - docker push $IMAGE_TAG_PRETEST

#run-pretest:
#  stage: run-pretest
#  tags:
#    - projects_puv
#  rules:
#    - if: '$CI_COMMIT_BRANCH =~ /^release-\\w+/'
#  before_script:
#    - echo "$CI_REGISTRY_PASSWORD" | docker login -u"$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
#    - chmod +x pretest/*.sh
#    - apk add curl net-tools
#  script:
#    - docker run -it -d --name $CI_PROJECT_NAME-$DB_IMAGE -p $DB_PORT:5432 $REPO_IMAGE:$DB_IMAGE
#    - ./pretest/run_app.sh
    # Скачиваем логи
#    - docker cp $CI_PROJECT_NAME:/usr/share/jetty/logs/server.log .
#  after_script:
    # Зачищаем все созданные контейнеры и образы
#    - docker stop $CI_PROJECT_NAME
#    - docker rm $CI_PROJECT_NAME
#    - docker stop $CI_PROJECT_NAME-$DB_IMAGE
#    - docker rm $CI_PROJECT_NAME-$DB_IMAGE
#    - docker system prune -f
#  artifacts:
#    paths:
#      - ./server.log
