---
  
  - include: docker-images.yml
  # Если изображение обновилось, то выполняем обновление контейнера.
  - include: docker-update.yml
  - include: docker-prune.yml
    when: images_pull_result.changed
    