---

- name: Create Systemd Java 11 | Copy unit 
  template:
    src: "java11_systemd.service.j2"
    dest: "/etc/systemd/system/{{ artifacts_name }}.service"

- name: Create Systemd Java 11 | Copy env app file
  template:
    src: "java11_systemd.env.j2"
    dest: "/etc/systemd/system/{{ artifacts_name }}.env"

- name: Create Systemd Java 11 | Enable and start java unit 
  systemd:
    name: "{{ artifacts_name }}.service"
    enabled: yes
    state: started
