---

  # Создаём рабочую директорию
  - name: Configure | Create work directory
    file: 
      state: directory
      path: "{{ app_dir }}"
    register: create_work_dir
    tags:
      - first
      - second
  
  # Копируем файл для запуска контейнера
  - name: Configure | Copy docker-compose
    template:
      src: "docker-compose.yml.j2"
      dest: "{{ app_dir }}/docker-compose.yml"
    tags:
      - first
      - second  

  # Копируем сертификаты
  - name: Configure | Copy certs dpr
    copy:
      src: "dpr_certs"
      dest: "{{ app_dir }}"
    tags:
      - first
      - second

  # Копируем сертификаты
  - name: Configure | Copy certs infra
    copy:
      src: "infra_certs"
      dest: "{{ app_dir }}"
    tags:
      - first
