---

deploy_registry_image: registry-dpr-gitlab.otr.ru:5005/puv/nsi
deploy_name: nsi-backend
deploy_ports:
  - 18080:18080
  - 8500:8500
deploy_volumes:
  - "{{ app_dir }}/logs/:/app/log"

deploy_registry_image_2: registry-dpr-gitlab.otr.ru:5005/puv/nsi-ufos
deploy_name_2: nsi-ufos-backend
deploy_ports_2:
  - 18081:18080
deploy_exposed_ports_2:
deploy_volumes_2:
  - "{{ app_dir }}/logs_ufos/:/usr/share/jetty/logs"

db_login: puv
db_password: Oracle33

db_ufos_host_prop: "jdbc:postgresql://puv-test2-int-nsi-db:5432/nsi_bos"