---

# Устанавливаем nginx
- name: Utils Install | Install nginx
  yum:
    name: nginx
    state: present

# Устанавливаем git
- name: Utils Install | Install git
  yum:
    name: git
    state: present
  when: inventory_hostname not in groups['nginx_static']
