---

deploy_registry_image: registry-dpr-gitlab.otr.ru:5005/puv/overpay-app
deploy_name: overpay-backend
deploy_ports: 8080:8080
deploy_volumes:
  - "{{ app_dir }}/logs/:/app/log"

env_port: "8080"

psql_ip: "10.20.10.111"
psql_port: "5432"
psql_db_user: "puv"
psql_db_pass: "Oracle33"
psql_db_name: "overpay"
psql_pg_pass: "Oracle13"
# Переменная для установки дополнительного модуля dblink
psql_db_extension: "dblink"

psql_name_2: "puv-{{ var_env }}-int-eld-gp-master.otr.ru"
psql_db_user_2: "eldfin_test"
psql_db_name_2: "eldfin_test"
psql_db_pass_2: "Oracle33"
