---

# Логинимся на наш реджистри
- name: Docker Images | Log into private registry and force re-authorization
  docker_login:
    registry: "{{ deploy_registry_url }}"
    username: "{{ deploy_registry_user }}"
    password: "{{ deploy_registry_pass }}"
    reauthorize: true
  no_log: false
  changed_when: false

# Скачваем нужные изображения.
- name: Docker Images | Pull an images
  docker_image:
    name: "{{ deploy_image }}"
    source: pull
    force_source: true
