---

# Логинимся на наш реджистри
- name: Docker Images | Log into private registry and force re-authorization
  docker_login:
    registry: "{{ deploy_registry_url }}"
    username: "{{ deploy_registry_user }}"
    password: "{{ deploy_registry_pass }}"
    reauthorize: true
  no_log: false
  changed_when: false

# Скачваем нужные изображения. Игнорирование ошибок включено, чтобы не ломалсяя плейбук для тех компонент, где ещё нет образа.
- name: Docker Images | Pull an images
  docker_image:
    name: "{{ deploy_registry_image }}:{{ deploy_branch }}"
    source: pull
    force_source: true
  register: images_pull_result
  ignore_errors: yes  

# Скачваем нужное изображения. Игнорирование ошибок включено, чтобы не ломалсяя плейбук для тех компонент, где ещё нет образа.
- name: Docker Images | Pull an images 2
  docker_image:
    name: "{{ deploy_registry_image_2 }}:{{ deploy_branch_2 }}"
    source: pull
    force_source: true
  register: images_pull_result_2
  ignore_errors: yes  
  when: inventory_hostname in groups['app_two']

# Скачваем нужное изображения. Игнорирование ошибок включено, чтобы не ломалсяя плейбук для тех компонент, где ещё нет образа.
- name: Docker Images | Pull an images 3
  docker_image:
    name: "{{ deploy_registry_image_3 }}:{{ deploy_branch_3 }}"
    source: pull
    force_source: true
  register: images_pull_result_3
  ignore_errors: yes  
  when: inventory_hostname in groups['app_three']
  