---

### rhel-7-server-extras-rpms необходим для установки пакета container-selinux для установки docker ###
# Устанавливаем докер
- name: Docker Install | Install docker pkgs
  yum:
    name: "{{ docker_pkgs }}"
    state: installed
    update_cache: true
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version != "8"

# Устанавливаем докер
- name: Docker Install | Install docker pkgs
  yum:
    name: "{{ docker_pkgs_8 }}"
    state: installed
    update_cache: true
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    
# Копируем конфигурационный файл docker
# Необходимо, дабы не пересекалась рабочая сеть хостов с сетью docker’а.
- name: Docker Install | Copy config file
  copy:
    src: "daemon.json"
    dest: "/etc/docker/daemon.json"

# Запускаем docker и делаем ему автостарт
- name: Docker Install | Start docker
  service:
    name: docker
    state: started
    enabled: yes


    