---

# Удаляем все не нужные изображения, игнорируем здесь ошибки, если на хост первый раз заливается изображение.
# Из-за старой версии API докера нельзя использовать модуль docker_prune, поэтому этот процесс организован так.
- name: Docker Prune | Clean up
  shell: docker rmi $(docker images -f dangling=true -q)
  ignore_errors: yes 
