---
# Создаём рабочую директорию
- name: Configure | Create work dir
  file:
    state: directory
    path: "{{ app_dir }}"
    owner: root
    group: root

# Создаём рабочую директорию Nginx
- name: Configure | Create config dir
  file:
    state: directory
    path: "{{ app_dir }}/nginx"
    owner: root
    group: root

# Клонируем репозиторий
- name: Proxy Configure | Clone a repo
  git:
    repo: "https://{{ deploy_registry_user }}:{{ deploy_registry_pass }}@dpr-gitlab.otr.ru/puv/{{ proxy_conf_repo }}.git"
    dest: "{{ config_dir }}/{{ proxy_conf_repo }}"
    clone: yes
    update: yes

#  Копируем файл конфигурации
- name: Proxy Configure | Copy file to nginx config dir
  copy: 
    src: "{{ config_dir }}/{{ proxy_conf_repo }}/{{ var_env }}.conf"
    dest: "{{ app_dir }}/nginx/{{ var_env }}.conf"
    remote_src: yes
    force: yes
  register: update_conf

#  Копируем файл docker-compose.yml
- name: Configure | Configure docker-compose.yml file
  template:
    src: "docker-compose.yml.j2"
    dest: "{{ app_dir }}/docker-compose.yml"
    owner: root
    group: root
