---

deploy_registry_image: registry-dpr-gitlab.otr.ru:5005/puv/category-docs-indexer
deploy_name: category-docs-indexer
deploy_ports:
  - 8080:8080
deploy_volumes:
  - "{{ app_dir }}/logs/:/app/log"

psql_db_name: "puv-dev-int-eld-gp-master.otr.ru"
psql_db_user: "eldfin_dev"
psql_db_name: "eldfin_dev"
psql_db_pass: "Oracle33"
psql_db_user_fw: "eldfin_dev"
psql_db_name_fw: "eldfin_dev"
psql_db_pass_fw: "Oracle33"

deploy_registry_image_2: registry-dpr-gitlab.otr.ru:5005/puv/eld-category-docs
deploy_name_2: eld-category-docs
deploy_ports_2:
  - 9080:8080
deploy_volumes_2:
  - "{{ app_dir }}/logs/:/app/log"