---

deploy_registry_image: registry-dpr-gitlab.otr.ru:5005/puv/reg
deploy_name: reg-backend
deploy_ports:
  - 18080:18080
  - 8500:8500
  - 5006:5005
deploy_volumes:
  - "{{ app_dir }}/logs/:/app/log"

deploy_registry_image_2: registry-dpr-gitlab.otr.ru:5005/puv/reg-ufos
deploy_name_2: reg-ufos-backend
deploy_ports_2:
  - 18081:18080
  - 5005:5005
deploy_exposed_ports_2:
  - 7777/tcp
deploy_volumes_2:
  - "{{ app_dir }}/logs_ufos/:/usr/share/jetty/logs"

