---

deploy_registry_image: registry-dpr-gitlab.otr.ru:5005/puv/puv-pages
deploy_name: elk-frontend
deploy_ports:
  - 18080:80
deploy_volumes:
  - "{{ app_dir }}/logs/:/var/log/nginx/"


deploy_registry_image_2: registry-dpr-gitlab.otr.ru:5005/puv/puv-proxy
deploy_name_2: proxy
deploy_ports_2:
  - 8080:80
  - 8081:81
deploy_volumes_2:
  - "{{ app_dir }}/logs_proxy/:/var/log/nginx/"
  