---
  
# Логинимся на наш реджистри
- name: Docker Images | Log into private registry and force re-authorization
  docker_login:
    registry: "{{ deploy_registry_url }}"
    username: "{{ deploy_registry_user }}"
    password: "{{ deploy_registry_pass }}"
    reauthorize: true
  no_log: false
  changed_when: false

# Запускаем контейнеры указанные в файле docker-compose
- name: Install | Docker compose up
  docker_compose:
    project_src: "{{ app_dir }}"
    remove_orphans: true
    state: present
    recreate: always
    pull: yes
