---
# Логинимся на наш реджистри
- name: Docker Images | Log into private registry and force re-authorization
  docker_login:
    registry: "{{ deploy_registry_url }}"
    username: "{{ deploy_registry_user }}"
    password: "{{ deploy_registry_pass }}"
    reauthorize: true
  no_log: false
  changed_when: false

  #  Запуск сервисов через docker-compose
- name: Docker compose up | Docker compose up
  docker_compose:
    project_src: "{{ app_dir }}"
    state: present
    pull: yes
